### ISSUE TITLE
Internal fields are overwritten with entity fields

### ISSUE THREAD

**Issue by tharders** [jungvonmatt/contentful-ssg#16]
The internal fields that are added automatically (id, createdAt, updatedAt, contentType) are overwritten with values from the entity when it has fields with the same name.

In a project a dynamic teaser entry has a "contentType" field. So in the content files for this type contain the entry content field in the contentType field, but all other content files contain the entries content type. 

In the transform function of the contentful-ssg.config.js you can use the options.contentType as a work around.
Still it would maybe be better to put the internal fields below a "sys" object.
That is what the contentful-hugo library does.

**Comment by tharders** [comment]
The problem is bigger than suspected.
In my case the "contentType" field is optional.
When the contentType field in the entry is empty the contentType property that is written contains the entry contentType.
When the field is not empty the contentType property contains the field value.
😳

**Comment by bezoerb** [comment]
this is fixed in [v0.17.0](https://github.com/jungvonmatt/contentful-ssg/releases/tag/v0.17.0) 
See https://github.com/jungvonmatt/contentful-ssg/pull/17 for details

**Comment by tharders** [comment]
Problem is resolved with this fix.
